<?php
G::LoadClass("plugin");

class pm2qbPlugin extends PMPlugin
{
  
  
  public function pm2qbPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "pm2qb Plugin";
    $this->sDescription  = "Autogenerated plugin for class pm2qb";
    $this->sPluginFolder = "pm2qb";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 0.05;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces = array("workflow", "HSU");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerPmFunction();
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("pm2qb", __FILE__);
